name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: NORMAL
      id: normal
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: NORMAL
        setup-command: rm -rf test && git clone https://github.com/N2Sys-EDU/Lab2-RTP-Test.git
          test
        command: "./test/runtest.sh NORMAL"
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        NORMAL_RESULTS: "${{steps.normal.outputs.result}}"
      with:
        runners: normal
