name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: FTPServer.Open
      id: ftpserver-open
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPServer.Open
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPServer.Open
        timeout: 1
        max-score: 10
    - name: FTPServer.Get
      id: ftpserver-get
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPServer.Get
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPServer.Get
        timeout: 1
        max-score: 10
    - name: FTPServer.Put
      id: ftpserver-put
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPServer.Put
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPServer.Put
        timeout: 1
        max-score: 10
    - name: FTPServer.SHA256
      id: ftpserver-sha256
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPServer.SHA256
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPServer.SHA256
        timeout: 1
        max-score: 10
    - name: FTPServer.List
      id: ftpserver-list
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPServer.List
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPServer.List
        timeout: 1
        max-score: 10
    - name: FTPServer.CdGet
      id: ftpserver-cdget
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPServer.CdGet
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPServer.CdGet
        timeout: 1
        max-score: 10
    - name: FTPServer.CdPut
      id: ftpserver-cdput
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPServer.CdPut
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPServer.CdPut
        timeout: 1
        max-score: 10
    - name: FTPClient.Open
      id: ftpclient-open
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPClient.Open
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPClient.Open
        timeout: 1
        max-score: 10
    - name: FTPClient.Get
      id: ftpclient-get
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPClient.Get
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPClient.Get
        timeout: 1
        max-score: 10
    - name: FTPClient.Put
      id: ftpclient-put
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FTPClient.Put
        setup-command: if [ ! -f ".built" ]; then (     touch .built &&     rm -rf
          test_classroom &&     rm -rf build &&     git clone https://github.com/N2Sys-EDU/2024-Lab1-myFTP-Test.git
          test_classroom &&     cd ./test_classroom &&     mkdir -p build &&     cd
          build &&     cmake .. &&     make &&     cd ../../ &&     mkdir -p build
          &&     cp ./test_classroom/ftp_client_std ./build &&     cp ./test_classroom/ftp_server_std
          ./build &&     cp ./test_classroom/build/ftp_test ./build &&     cd ./build
          &&     cmake .. &&     make &&     cd ../) fi
        command: cd build && ./ftp_test --gtest_filter=FTPClient.Put
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FTPSERVER-OPEN_RESULTS: "${{steps.ftpserver-open.outputs.result}}"
        FTPSERVER-GET_RESULTS: "${{steps.ftpserver-get.outputs.result}}"
        FTPSERVER-PUT_RESULTS: "${{steps.ftpserver-put.outputs.result}}"
        FTPSERVER-SHA256_RESULTS: "${{steps.ftpserver-sha256.outputs.result}}"
        FTPSERVER-LIST_RESULTS: "${{steps.ftpserver-list.outputs.result}}"
        FTPSERVER-CDGET_RESULTS: "${{steps.ftpserver-cdget.outputs.result}}"
        FTPSERVER-CDPUT_RESULTS: "${{steps.ftpserver-cdput.outputs.result}}"
        FTPCLIENT-OPEN_RESULTS: "${{steps.ftpclient-open.outputs.result}}"
        FTPCLIENT-GET_RESULTS: "${{steps.ftpclient-get.outputs.result}}"
        FTPCLIENT-PUT_RESULTS: "${{steps.ftpclient-put.outputs.result}}"
      with:
        runners: ftpserver-open,ftpserver-get,ftpserver-put,ftpserver-sha256,ftpserver-list,ftpserver-cdget,ftpserver-cdput,ftpclient-open,ftpclient-get,ftpclient-put
